### PR TITLE
Fixed orientation of repo section and fixed error redirections

### LINKED ISSUE #4: The error redirection of cat commands on non-exitant artifacts will need to be improved
While the script works great, We should perhaps add 2>/dev/null for the affected cat command to avoid these messages. 

```
# ./pulp3_repo_list.sh 
cat: artifact/77/c1fb34354ea55af9e9402976cfa4fc5d7c14c020947cf8454422e0ca5001a0: No such file or directory
cat: artifact/46/3c26afb22f1eb831ae68b8bc3de513580e2d673102bbe74a3c130965b8637e: No such file or directory
cat: artifact/3a/c58ae9a35f490422bc4dc6e2098789a04c9dd8896727e4defa858c4a79c46c: No such file or directory
cat: artifact/33/3acafc79302a2464ed99f0188d67da1befc320d4a32b5b3ba29d9d64930f43: No such file or directory
cat: artifact/18/a9fda5de2a660226aea2a5c1c353116835a351f1979cab745893eb483b16ee: No such file or directory
cat: artifact/ba/b53e18ab463652bc6addc90b4459379d951ff7bc6965e38b5463fef407db83: No such file or directory
cat: artifact/f8/b7e3d2afc8120b7aa9dd9832e891f5ed76b46dbf1fafed6de3b41dd2e2ce27: No such file or directory
cat: artifact/77/c1fb34354ea55af9e9402976cfa4fc5d7c14c020947cf8454422e0ca5001a0: No such file or directory
cat: artifact/46/3c26afb22f1eb831ae68b8bc3de513580e2d673102bbe74a3c130965b8637e: No such file or directory
cat: artifact/77/c1fb34354ea55af9e9402976cfa4fc5d7c14c020947cf8454422e0ca5001a0: No such file or directory
cat: artifact/46/3c26afb22f1eb831ae68b8bc3de513580e2d673102bbe74a3c130965b8637e: No such file or directory
cat: artifact/3a/c58ae9a35f490422bc4dc6e2098789a04c9dd8896727e4defa858c4a79c46c: No such file or directory
cat: artifact/33/3acafc79302a2464ed99f0188d67da1befc320d4a32b5b3ba29d9d64930f43: No such file or directory
cat: artifact/18/a9fda5de2a660226aea2a5c1c353116835a351f1979cab745893eb483b16ee: No such file or directory
cat: artifact/ba/b53e18ab463652bc6addc90b4459379d951ff7bc6965e38b5463fef407db83: No such file or directory
cat: artifact/f8/b7e3d2afc8120b7aa9dd9832e891f5ed76b46dbf1fafed6de3b41dd2e2ce27: No such file or directory
cat: artifact/3a/c58ae9a35f490422bc4dc6e2098789a04c9dd8896727e4defa858c4a79c46c: No such file or directory
cat: artifact/33/3acafc79302a2464ed99f0188d67da1befc320d4a32b5b3ba29d9d64930f43: No such file or directory
cat: artifact/18/a9fda5de2a660226aea2a5c1c353116835a351f1979cab745893eb483b16ee: No such file or directory
cat: artifact/ba/b53e18ab463652bc6addc90b4459379d951ff7bc6965e38b5463fef407db83: No such file or directory
cat: artifact/f8/b7e3d2afc8120b7aa9dd9832e891f5ed76b46dbf1fafed6de3b41dd2e2ce27: No such file or directory
Please, upload to Red Hat the files in a sequence:
  - /var/log/pulp3_content_info.log
  - /var/log/pulp3_report_info.log

### PR DESCRIPTION
**Pull request by sayan3296**
* Fixes https://github.com/waldirio/satellite_tricks/issues/4
* Also introduces the repository related data in tabular format instead of long list format

### CODE REVIEW

**Comment by sayan3296** [comment]
The repo part looks like this now:

```
#######################################
Presentation of Individual Repositories
#######################################

Repo_Path                                                                            RPM_Count_in_Metadata  RPM_Count_in_DB
---------                                                                            ---------------------  ---------------
RedHat/Library/content/dist/rhel8/8/x86_64/baseos/os                                 9568                   9568
RedHat/Library/content/eus/rhel8/8.4/x86_64/codeready-builder/os                     4233                   4233
RedHat/Library/content/els/rhel/server/6/6Server/x86_64/sat-tools/6.10/os            16                     16
RedHat/Library/content/els/rhel/server/6/6Server/x86_64/os                           21295                  21295
RedHat/Library/content/dist/rhel/server/7/7Server/x86_64/sat-maintenance/6/os        56                     56
RedHat/Library/content/dist/rhel8/8.4/x86_64/codeready-builder/os                    4186                   4186
RedHat/Library/content/dist/rhel/server/7/7Server/x86_64/extras/os                   1422                   1422
RedHat/Library/content/dist/rhel8/8.5/x86_64/baseos/kickstart                        1708                   1708
RedHat/Library/custom/Satellite_Client_-_7_0/Satellite_Client_7_RHEL7                17                     17
RedHat/Library/content/dist/layered/rhel8/x86_64/sat-tools/6.10/os                   10                     10
RedHat/Library/content/dist/rhel/server/7/7Server/x86_64/os                          32788                  32788
RedHat/Library/content/dist/rhel8/8.4/x86_64/appstream/os                            19509                  19509
RedHat/Library/custom/Satellite_Client_-_7_0/blah                                    10                     20

**Comment by waldirio** [comment]
Hello @sayan3296 

I like that. However, this will affect the next report.

```
# cat /var/log/pulp3_report_info.log 
#######################
Basic Pulp3 Information
#######################

# Organization(s):
------------------
ACME

# LifeCycle(s):
---------------
Library prod

# Content View(s):
------------------
cv_rhel8tools_zabbix cv_tools cv_tools_6_7 cv_tools_7_8



#######################################
Presentation of Individual Repositories
#######################################

Repo_Path                                                                              RPM_Count_in_Metadata  RPM_Count_in_DB
---------                                                                              ---------------------  ---------------
ACME/Library/cv_tools/content/dist/rhel/server/7/7Server/x86_64/sat-tools/6.10/os      62                     62
ACME/prod/cv_tools/content/dist/rhel/server/7/7Server/x86_64/sat-tools/6.10/os         62                     62
ACME/Library/cv_rhel8tools_zabbix/custom/zabbix/zabbix                                 12                     12
ACME/Library/cv_rhel8tools_zabbix/content/dist/layered/rhel8/x86_64/sat-tools/6.10/os  10                     10
ACME/Library/cv_tools_7_8/content/dist/layered/rhel8/x86_64/sat-tools/6.10/os          10                     10
ACME/Library/cv_tools_7_8/content/dist/rhel/server/7/7Server/x86_64/sat-tools/6.10/os  62                     62
ACME/Library/custom/zabbix/zabbix                                                      12                     12
ACME/Library/content/dist/rhel/server/7/7Server/x86_64/sat-tools/6.10/os               62                     62
ACME/Library/content/dist/layered/rhel8/x86_64/sat-tools/6.10/os                       10                     10
ACME/Library/content/els/rhel/server/6/6Server/x86_64/sat-tools/6.10/os                16                     16
ACME/Library/cv_tools_6_7/content/els/rhel/server/6/6Server/x86_64/sat-tools/6.10/os   16                     16
ACME/Library/cv_tools_6_7/content/dist/rhel/server/7/7Server/x86_64/sat-tools/6.10/os  62                     62




#####################################################
Presentation of Content View / Composite Content View
#####################################################

Organization  LifeCycle  Content_View          RPM_Count_in_Metadata  RPM_Count_in_DB
------------  ---------  ------------          ---------------------  ---------------
ACME          Library    cv_rhel8tools_zabbix
ACME          Library    cv_tools
ACME          Library    cv_tools_6_7
ACME          Library    cv_tools_7_8
ACME          prod       cv_tools

------ End of Report ------
```

Please, feel free to move on.

Thank you again!
Waldirio

**Comment by sayan3296** [comment]
I thought something was not right and hence kept the PR in draft and now and now I understand how stupid i am. 

Let me see if I can fix the logic anyway. Will keep you posted.

**Comment by sayan3296** [comment]
Latest Status:

```
######################
Basic Pulp3 Information
#######################

# Organization(s):
------------------
RedHat , SCA

# LifeCycle(s):
---------------
Library , QA

# Content View(s):
------------------
RHEL6 , RHEL7 , RHEL8



#######################################
Presentation of Individual Repositories
#######################################

Repo_Path                                                                              RPM_Count_in_Metadata  RPM_Count_in_DB
---------                                                                              ---------------------  ---------------
**RedHat/Library/content/dist/rhel8/8.5/x86_64/baseos/kickstart                        1708                   1708
**RedHat/Library/content/eus/rhel8/8.4/x86_64/codeready-builder/os                     4233                   4233
**RedHat/Library/content/els/rhel/server/6/6Server/x86_64/sat-tools/6.10/os            16                     16
**RedHat/Library/content/els/rhel/server/6/6Server/x86_64/os                           21295                  21295
**RedHat/Library/content/dist/rhel/server/7/7Server/x86_64/extras/os                   1422                   1422
**RedHat/Library/content/dist/rhel8/8.4/x86_64/appstream/os                            19509                  19509
**RedHat/Library/content/dist/rhel8/8/x86_64/baseos/os                                 9568                   9568
**RedHat/Library/content/dist/rhel8/8.3/x86_64/baseos/os                               6706                   6706
**RedHat/Library/content/dist/rhel8/8.3/x86_64/appstream/os                            15985                  15985
**RedHat/Library/custom/Satellite_Client_-_7_0/blah                                    10                     20
**RedHat/Library/content/dist/rhel/server/7/7Server/x86_64/ansible/2.9/os              51                     51
**RedHat/Library/content/dist/rhel8/8/x86_64/codeready-builder/os                      4769                   4769
**RedHat/Library/content/dist/rhel/server/7/7Server/x86_64/os                          32788                  32788
**RedHat/Library/content/dist/rhel/server/6/6.10/x86_64/kickstart                      3861                   7866
**RedHat/Library/content/dist/rhel8/8.4/x86_64/codeready-builder/os                    4186                   4186
**RedHat/Library/custom/Satellite_Client_-_7_0/Satellite_Client_7_RHEL7                17                     17
**RedHat/Library/content/dist/rhel8/8/x86_64/highavailability/os                       436                    436
**RedHat/Library/content/dist/layered/rhel8/x86_64/sat-tools/6.10/os                   10                     10
**RedHat/Library/content/dist/rhel8/8/x86_64/appstream/os                              22284                  22284
**RedHat/Library/content/dist/rhel/server/7/7Server/x86_64/sat-maintenance/6/os        56                     56
**SCA/Library/content/eus/rhel8/8.4/x86_64/highavailability/os                         0                      0
**SCA/Library/content/eus/rhel8/8.4/x86_64/supplementary/os                            0                      0
**SCA/Library/content/eus/rhel8/8.4/x86_64/baseos/os                                   0                      0
**SCA/Library/content/eus/rhel8/8.4/x86_64/sat-tools/6.8/os                            0                      0
**RedHat/Library/content/dist/rhel/server/7/7.9/x86_64/kickstart                       5230                   5339
**RedHat/Library/content/dist/rhel/server/7/7Server/x86_64/rhscl/1/os                  13853                  13853
**RedHat/QA/RHEL7/content/dist/rhel/server/7/7Server/x86_64/rhscl/1/os                 13830                  13830
**RedHat/QA/RHEL7/content/dist/rhel/server/7/7Server/x86_64/ansible/2.9/os             51                     51
**RedHat/QA/RHEL7/content/dist/rhel/server/7/7Server/x86_64/os                         32680                  32680
**RedHat/Library/RHEL8/content/dist/rhel8/8.5/x86_64/appstream/kickstart               6220                   6220
**RedHat/Library/RHEL8/content/dist/rhel8/8.5/x86_64/baseos/kickstart                  1708                   1708
**RedHat/Library/RHEL8/custom/Satellite_Client_-_7_0/Satellite_Client_7_RHEL8          10                     10
**RedHat/Library/RHEL8/content/dist/rhel8/8/x86_64/codeready-builder/os                4764                   4764
**RedHat/Library/RHEL8/content/dist/rhel8/8/x86_64/highavailability/os                 436                    436
**RedHat/Library/RHEL8/content/dist/rhel8/8/x86_64/appstream/os                        22253                  22253
**RedHat/Library/RHEL8/content/dist/rhel8/8/x86_64/baseos/os                           9548                   9548
**RedHat/QA/RHEL8/content/dist/rhel8/8.5/x86_64/baseos/kickstart                       1708                   1708
**RedHat/QA/RHEL8/content/dist/rhel8/8.5/x86_64/appstream/kickstart                    6220                   6220
**RedHat/QA/RHEL8/content/dist/rhel8/8/x86_64/highavailability/os                      436                    436
**RedHat/QA/RHEL8/custom/Satellite_Client_-_7_0/Satellite_Client_7_RHEL8               10                     10
**RedHat/QA/RHEL8/content/dist/rhel8/8/x86_64/appstream/os                             22253                  22253
**RedHat/QA/RHEL8/content/dist/rhel8/8/x86_64/baseos/os                                9548                   9548
**RedHat/QA/RHEL8/content/dist/rhel8/8/x86_64/codeready-builder/os                     4764                   4764
**RedHat/Library/RHEL7/custom/Satellite_Client_-_7_0/Satellite_Client_7_RHEL7          17                     17
**RedHat/Library/RHEL7/content/dist/rhel/server/7/7.9/x86_64/kickstart                 5230                   5339
**RedHat/Library/RHEL7/content/dist/rhel/server/7/7Server/x86_64/sat-maintenance/6/os  56                     56
**RedHat/Library/RHEL7/content/dist/rhel/server/7/7Server/x86_64/ansible/2.9/os        51                     51
**RedHat/Library/RHEL7/content/dist/rhel/server/7/7Server/x86_64/extras/os             1421                   1421
**RedHat/Library/RHEL7/content/dist/rhel/server/7/7Server/x86_64/rhscl/1/os            13830                  13830
**RedHat/Library/RHEL7/content/dist/rhel/server/7/7Server/x86_64/os                    32680                  32680
**RedHat/QA/RHEL7/content/dist/rhel/server/7/7.9/x86_64/kickstart                      5230                   5339
**RedHat/QA/RHEL7/custom/Satellite_Client_-_7_0/Satellite_Client_7_RHEL7               17                     17
**RedHat/QA/RHEL7/content/dist/rhel/server/7/7Server/x86_64/sat-maintenance/6/os       56                     56
**RedHat/QA/RHEL7/content/dist/rhel/server/7/7Server/x86_64/extras/os                  1421                   1421
**RedHat/Library/RHEL6/content/dist/rhel/server/6/6.10/x86_64/kickstart                3861                   7866
**RedHat/Library/RHEL6/content/els/rhel/server/6/6Server/x86_64/sat-tools/6.10/os      16                     16
**RedHat/Library/RHEL6/content/els/rhel/server/6/6Server/x86_64/os                     21294                  21294
**RedHat/QA/RHEL6/content/dist/rhel/server/6/6.10/x86_64/kickstart                     3861                   7866
**RedHat/Library/custom/Satellite_Client_-_7_0/blah2                                   10                     10
**RedHat/QA/RHEL6/content/els/rhel/server/6/6Server/x86_64/sat-tools/6.10/os           16                     16
**RedHat/QA/RHEL6/content/els/rhel/server/6/6Server/x86_64/os                          21294                  21294
**RedHat/Library/content/dist/rhel/server/7/7Server/x86_64/sat-tools/6.10/os           62                     62
**RedHat/Library/custom/Satellite_Client_-_7_0/Satellite_Client_7_RHEL8                10                     10
**RedHat/Library/content/dist/rhel8/8.2/x86_64/appstream/os                            12221                  12221
**RedHat/Library/content/dist/rhel8/8.5/x86_64/appstream/kickstart                     6220                   6220
**RedHat/Library/content/dist/rhel8/8.4/x86_64/baseos/os                               8249                   8249
**RedHat/Library/content/dist/rhel8/8.2/x86_64/baseos/os                               5101                   5101




#####################################################
Presentation of Content View / Composite Content View
#####################################################

Organization  LifeCycle  Content_View  RPM_Count_in_Metadata  RPM_Count_in_DB
------------  ---------  ------------  ---------------------  ---------------
RedHat        Library    RHEL6         25171                  29176
RedHat        Library    RHEL7         53285                  53394
RedHat        Library    RHEL8         44939                  44939
RedHat        QA         RHEL6         25171                  29176
RedHat        QA         RHEL7         53285                  53394
RedHat        QA         RHEL8         44939                  44939

------ End of Report ------

**Comment by sayan3296** [comment]
If this looks better now and can be adopted, Then I will update the README and Changelog as well in this same commit

**Comment by sayan3296** [comment]
I fixed one more thing in my recent commit. 

If the values to be added are like this , then due to that space in between, the bc command will fail to sum it up and hence fixed it by ignoring the blank space
```
1
3
62
17597
21993
10
274
9436
32645
56

13817
51

**Comment by waldirio** [comment]
Hi @sayan3296 

Great. Thank you.

Please, feel free to update the readme and changelog, then we will be good to go.

teamwork++

**Comment by sayan3296** [comment]
Done.. Thanks a lot for all the feedbacks.

**Comment by sayan3296** [comment]
And yes, This will take care of https://github.com/waldirio/satellite_tricks/issues/4 as well..

**Comment by waldirio** [comment]
Perfect.

Thank you!

**Pull request merged**
